name: TigersTogether
description: Helping CHHS students, staff and teachers stay together during distance learning

version: 1.0.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # navigation
  convex_bottom_bar: ^2.5.1
  # provider: ^4.0.5
  provider: ^4.3.2+2
  rxdart: ^0.24.1

  # getstream.io CHAT
  flutter_apns: ^1.1.0
  flutter_local_notifications: ^1.4.3
  stream_chat_flutter: ^0.2.8+3

  #Firebase auth by andrea:
  firebase_core: "^0.5.0"
  firebase_auth: ^0.18.1+1
  flutter_signin_button: ^1.0.0

  apple_sign_in: ^0.1.0
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0

  flutter_secure_storage: ^3.3.4
  package_info: ^0.4.3
  random_string: ^2.1.0

   #Firebase other services: 
  cloud_firestore: ^0.14.1+2
  firebase_storage: ^4.0.1

  #firebase_analytics: ^6.0.0
  firebase_dynamic_links: ^0.6.0

  image_picker: ^0.6.7+7
  uuid: ^2.0.2

  # required by Proconian
  http: ^0.12.0+2
  flutter_html: ^0.11.0
  intl: ^0.16.1
  
  cached_network_image: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/fb-logo.png
    - assets/go-logo.png
    - assets/user.png
